//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace second_shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class requirement
    {
        public int id { get; set; }
        public Nullable<int> users_id { get; set; }
        public string title { get; set; }
        public string profile { get; set; }
        public Nullable<int> price { get; set; }
        public string tags { get; set; }
        public string depart { get; set; }
        public string wechat { get; set; }
        public string qq { get; set; }
        public string phone { get; set; }
        public string publish_time { get; set; }
    
        public virtual users users { get; set; }
    }
}
